
export const SET_APARTMENTS_START = 'SET_APARTMENTS_START';
export const SET_APARTMENTS_SUCCESS = 'SET_APARTMENTS_SUCCESS';
export const SET_APARTMENTS_FAIL = 'SET_APARTMENTS_FAIL';

export const SET_CATEGORY_INDEX = 'SET_CATEGORY_INDEX';


export const INITIAL_AUTH ='INITIAL_AUTH';
export const AUTH__SUCCESS= 'AUTH__SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL'